//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zoyobar.shared.panzer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("zoyobar.shared.panzer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (function(k){function t(a){if(l.call(this,a,&quot;fill&quot;)){for(var d=a.__repeater,b=0;b&lt;d.filterfield.length;b++){var c=k(&quot;#&quot;+d.filterfield[b]+&quot;_filter&quot;);d.filtercondition[d.filterfield[b]]=c.length!=0?c.val():null}if(null!=d.prefill&amp;&amp;(b=d.prefill.call(this,a,{condition:d.filtercondition}),null!=b&amp;&amp;!b)){h.call(this,a,&quot;fill&quot;);return}null!=d.fill?d.fill.call(this,a,{condition:d.filtercondition,callback:u}):u.call(this,a,data,!0)}}function u(a,d,b){h.call(this,a,&quot;fill&quot;);var c=a.__repeater;if(null==b||b){if(!c.fieldf [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string repeater_min {
            get {
                return ResourceManager.GetString("repeater_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (function(c){function e(a){d(a);var b=a.__timer;b.handler=setInterval(function(){null!=b.tick&amp;&amp;b.tick.call(this,a,{})},b.interval)}function d(a){a=a.__timer;null!=a.handler&amp;&amp;clearInterval(a.handler)}c.fn.__timer=function(){if(this.length==0)return this;var a=this.get(0),b=&quot;create&quot;;if(typeof arguments[0]==&quot;string&quot;){if(null==a.__timer)return this;b=arguments[0]==&quot;option&quot;?arguments.length==2?&quot;get&quot;:&quot;set&quot;:&quot;method&quot;}else arguments[0]=c.extend({},c.fn.__timer.defaults,arguments[0]);switch(b){case &quot;get&quot;:return a.__t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string timer_min {
            get {
                return ResourceManager.GetString("timer_min", resourceCulture);
            }
        }
    }
}
