//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.239
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace zoyobar.shared.panzer.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("zoyobar.shared.panzer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 (function(c){c.panzer={check:function(b,a,e){var d;if(null!=a)if(null!=e&amp;&amp;e&amp;&amp;null!=a.readonly&amp;&amp;a.readonly)d=c.panzer.getTip.call(this,a,&quot;readonly&quot;,(null==a.name?&quot;argument&quot;:a.name)+&quot; is read-only&quot;);else if(null==b){if(null!=a.need&amp;&amp;a.need)null==a.defaultvalue?d=c.panzer.getTip.call(this,a,&quot;need&quot;,(null==a.name?&quot;argument&quot;:a.name)+&quot; can not be empty&quot;):b=a.defaultvalue}else if(null!=a.type&amp;&amp;a.type!=&quot;date&quot;&amp;&amp;typeof b!=a.type)null==a.defaultvalue?d=c.panzer.getTip.call(this,a,&quot;type&quot;,(null==a.name?&quot;argument&quot;:
        ///a.name [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string panzer_min {
            get {
                return ResourceManager.GetString("panzer_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (function(a){a.fn.__plot=function(){var b=a.panzer.getPE.call(this,&quot;__plot&quot;,arguments);return null==b?this:b.result};a.fn.__plot.funs={create:{method:function(){}},destroy:{method:function(b){this.empty();a.panzer.destroy.call(this,b)}},fill:{method:function(b){b=b.option;this.attr(&quot;id&quot;)==&quot;&quot;&amp;&amp;a.error(&quot;the tag miss a id&quot;);a.jqplot(this.attr(&quot;id&quot;),b.points,b.options)}}};a.fn.__plot.defaults={points:[],options:null};a.fn.__plot.defaults.__mask={points:{name:&quot;points&quot;,type:&quot;object&quot;,need:!0,defaultvalue:[]},
        ///opti [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string plot_min {
            get {
                return ResourceManager.GetString("plot_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (function(g){function o(b,a){var c=b.option;if(c.singlethread&amp;&amp;c.busy)return null!=c.blocked&amp;&amp;c.blocked.call(this,b,{action:a}),!1;c.busy=!0;if(null!=c.preexecute){var e={action:a,tip:null};c.preexecute.call(this,b,e);F.call(this,b,e.tip)}return!0}function O(b,a){if(x.call(this,b,a,&quot;state&quot;)!=&quot;removed&quot;){var c=b.option;!c.multipleedit&amp;&amp;null!=c.index.edit&amp;&amp;k.call(this,b,c.index.edit,&quot;editing&quot;,!1);c.index.edit=a;k.call(this,b,a,&quot;editing&quot;,!0);p.call(this,b,c.data)}}function p(b,a){var c=b.option,e=!1;
        ///c.data=a;c [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string repeater_min {
            get {
                return ResourceManager.GetString("repeater_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (function(b){function c(a){a=a.option;a.count=0;null!=a.handler&amp;&amp;clearInterval(a.handler)}b.fn.__timer=function(){var a=b.panzer.getPE.call(this,&quot;__timer&quot;,arguments);return null==a?this:a.result};b.fn.__timer.funs={destroy:{method:function(a){c.call(this,a);b.panzer.destroy.call(this,a)}},start:{method:function(a){c.call(this,a);var b=a.option;b.handler=setInterval(function(){b.count++;null!=b.tick&amp;&amp;b.tick.call(this,a,{count:b.count})},b.interval)}},stop:{method:c}};b.fn.__timer.defaults={count:0,
        ///handler:n [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string timer_min {
            get {
                return ResourceManager.GetString("timer_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (function(b){function c(a){b.panzer.createJQuery.call(this,a.option.timer).__timer(&quot;stop&quot;)}b.fn.__uploader=function(){var a=b.panzer.getPE.call(this,&quot;__uploader&quot;,arguments);return null==a?this:a.result};b.fn.__uploader.funs={destroy:{method:function(a){c.call(this,a);b.panzer.destroy.call(this,a)}},complete:{method:c},hide:{method:function(a){a=b.panzer.createJQuery.call(this,a.option.upload);a.length!=0&amp;&amp;a.hide()}},upload:{method:function(a){var a=a.option,c=b.panzer.createJQuery.call(this,a.upload).conten [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string uploader_min {
            get {
                return ResourceManager.GetString("uploader_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (function(c){function g(d){var a=d.option,b=c.panzer.createJQuery.call(this,a.target);if(b.length!=0){var f=a.mask,e=b.attr(&quot;type&quot;);e==&quot;checkbox&quot;||e==&quot;radio&quot;?(e=b.attr(&quot;checked&quot;),null==e?e=!1:e==&quot;checked&quot;&amp;&amp;(e=!0)):e=b.val();null!=f.need&amp;&amp;f.need&amp;&amp;typeof e==&quot;string&quot;&amp;&amp;e==&quot;&quot;?b={value:&quot;&quot;,tip:null==f.tip.need?(null==f.name?&quot;argument&quot;:f.name)+&quot; should not be empty&quot;:f.tip.need,success:!1}:(b=c.panzer.check.call(this,c.panzer.convert.call(this,e,f.defaultvalue,f.type,f.provider),f,!1),b.success&amp;&amp;null!=a.equal&amp;&amp;
        ///c.pa [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string validator_min {
            get {
                return ResourceManager.GetString("validator_min", resourceCulture);
            }
        }
    }
}
